# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-19 13:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0005_plstandard_pltype_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='plstandard',
            name='PLtype',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='years', to='repo.PLtype'),
        ),
        migrations.AddField(
            model_name='plstandard',
            name='Year',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='years', to='repo.Year'),
        ),
    ]
