# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-19 13:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0006_auto_20180119_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='plstandard',
            name='BU',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='BU', to='repo.BU'),
        ),
        migrations.AddField(
            model_name='plstandard',
            name='Company_Name',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='Company', to='repo.Company'),
        ),
        migrations.AlterField(
            model_name='plstandard',
            name='PLtype',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='PLType', to='repo.PLtype'),
        ),
    ]
